sensor:
  - platform: hlw8012
    model: bl0937
    sel_pin:
      number: ${sel_pin}
      inverted: true
    cf_pin: ${cf_pin}
    cf1_pin: ${cf1_pin}
    voltage_divider: ${voltage_divider}
    current_resistor: ${current_resistor}Ω
    voltage:
      name: Voltage(V)
      web_server:
        sorting_weight: 2
      icon: "mdi:sine-wave"
    current:
      name: Current(A)
      web_server:
        sorting_weight: 3
      icon: "mdi:current-ac"
    power:
      name: Power(W)
      web_server:
        sorting_weight: 4
      icon: "mdi:lightning-bolt"
    energy:
      name: TotalEnergy
      web_server:
        sorting_weight: 5
      icon: "mdi:home-lightning-bolt"
    update_interval: 10s
